// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bHisxgy0F2-bCLvvKQ7S8v3-EkY14yw',
    appId: '1:961092629918:web:cf3beba8e05f267b2f928f',
    messagingSenderId: '961092629918',
    projectId: 'barbershop-appproject',
    authDomain: 'barbershop-appproject.firebaseapp.com',
    storageBucket: 'barbershop-appproject.appspot.com',
    measurementId: 'G-523PT3Z9NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjwTZ9awZFvhuA-GCyvc7U0IjNa3TwsZM',
    appId: '1:961092629918:android:18ced39906271f452f928f',
    messagingSenderId: '961092629918',
    projectId: 'barbershop-appproject',
    storageBucket: 'barbershop-appproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8XyDddGrzj9vEsqQI9H4hAGu-oKxKEI',
    appId: '1:961092629918:ios:60e1b0f6f77c8b2b2f928f',
    messagingSenderId: '961092629918',
    projectId: 'barbershop-appproject',
    storageBucket: 'barbershop-appproject.appspot.com',
    iosClientId: '961092629918-i9p7lleest2vtvr8afokec2uh2dsd1jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberShopApp',
  );
}
